
php:
    image: php:7.4-fpm-alpine
    container_name: php-container
    links: 
        - postgres
    expose: 
        - 9000

postgres:
    image: postgres:13
    container_name: postgres-container
    environment: 
        - POSTGRES_DB=catalyst
        - POSTGRES_HOST=localhost
        - POSTGRES_PORT=5432
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        

 